### PR TITLE
Favicon tweaks

### PR DESCRIPTION
**Pull request by ghost**
- Fixes: 

- Optimises PNG favicon (33% file size reduction, same quality)
- Add SVG favicon for higher res

### CODE REVIEW

**Comment by kevinmarks** [comment]
Putting some kind of link signifier on the blue background would be a good idea, as I can't tell bsky.link form bsky.app in the browser at the moment.

**Comment by ghost** [comment]
> Putting some kind of link signifier on the blue background would be a good idea, as I can't tell bsky.link form bsky.app in the browser at the moment.

I agree; I just didn't want to make any drastic changes since this is an unsolicited PR.

Here's how it could look with fa-link, which is probably appropriate as bsky uses Font Awesome:

**Comment by capjamesg** [comment]
Thank you for your PR, @lx-is! I love the idea to use the Font Awesome link! Feel free to submit an alternate logo in the style you showed and I'll merge this PR.

**Comment by ghost** [comment]
I messed up the merge, oops! Will open a new PR.

**Pull request closed without merging**
